In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
import numpy as np
from tensorflow.keras.layers import Dense,LSTM,Embedding,Bidirectional,Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [2]:
(X_train,y_train) , (X_test,y_test)=imdb.load_data()

In [3]:
print(X_train.shape)
print(y_train.shape)
print(np.unique(y_train))


(25000,)
(25000,)
[0 1]


In [4]:
X_train=pad_sequences(X_train,maxlen=120)
X_test=pad_sequences(X_test,maxlen=120)


In [5]:
max_words=np.max(X_train)
print(max_words)


88586


In [6]:
model=Sequential()
model.add(Embedding(max_words+1,10,input_length=120))
model.add(LSTM(units=16, return_sequences=True))
model.add(LSTM(units=8, return_sequences=True))
model.add(LSTM(units=4,kernel_regularizer=tf.keras.regularizers.l2(0.001)))
model.add(Dense(1,activation="sigmoid"))

optimizer = tf.keras.optimizers.Adam(lr=1e-3)
model.compile(optimizer=optimizer,loss="binary_crossentropy",metrics=["accuracy"])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 120, 10)           885870    
_________________________________________________________________
lstm (LSTM)                  (None, 120, 16)           1728      
_________________________________________________________________
lstm_1 (LSTM)                (None, 120, 8)            800       
_________________________________________________________________
lstm_2 (LSTM)                (None, 4)                 208       
_________________________________________________________________
dense (Dense)                (None, 1)                 5         
Total params: 888,611
Trainable params: 888,611
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.fit(X_train,y_train,epochs=14,validation_split=0.2)

Epoch 1/14
625/625 [==============================] - 15s 24ms/step - loss: 0.4803 - accuracy: 0.7728 - val_loss: 0.3689 - val_accuracy: 0.8448
Epoch 2/14
625/625 [==============================] - 14s 22ms/step - loss: 0.2351 - accuracy: 0.9184 - val_loss: 0.3764 - val_accuracy: 0.8486
Epoch 3/14
625/625 [==============================] - 14s 22ms/step - loss: 0.1300 - accuracy: 0.9621 - val_loss: 0.4401 - val_accuracy: 0.8356
Epoch 4/14
625/625 [==============================] - 14s 22ms/step - loss: 0.0876 - accuracy: 0.9758 - val_loss: 0.4627 - val_accuracy: 0.8408
Epoch 5/14
625/625 [==============================] - 14s 22ms/step - loss: 0.0639 - accuracy: 0.9833 - val_loss: 0.5730 - val_accuracy: 0.8220
Epoch 6/14
625/625 [==============================] - 14s 22ms/step - loss: 0.0436 - accuracy: 0.9898 - val_loss: 0.6014 - val_accuracy: 0.8326
Epoch 7/14
625/625 [==============================] - 14s 22ms/step - loss: 0.0351 - accuracy: 0.9919 - val_loss: 0.7345 - val_accuracy:

In [8]:
model.evaluate(X_test,y_test)

782/782 [==============================] - 6s 8ms/step - loss: 0.8139 - accuracy: 0.8083


[0.8138501644134521, 0.8083199858665466]


# Mis-Predictions!!

```

```



In [9]:
result=np.array((0.5<model.predict(X_test[0:1000]))*1)
print(result)

[[0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]


In [10]:
incorrect=np.where(result != np.array(y_test[0:1000]))

In [14]:
len(incorrect)

2

In [11]:
index=incorrect[0]
print(X_test[index])
print(model.predict(X_test[index]))
print(y_test[index])


[[  0   0   0 ...  14   6 717]
 [  0   0   0 ...  14   6 717]
 [  0   0   0 ...  14   6 717]
 ...
 [  0   0   0 ...  14  22 287]
 [  0   0   0 ...  14  22 287]
 [  0   0   0 ...  14  22 287]]
[[0.0982759 ]
 [0.0982759 ]
 [0.0982759 ]
 ...
 [0.99522424]
 [0.99522424]
 [0.99522424]]
[0 0 0 ... 0 0 0]


In [15]:
from sklearn.metrics import accuracy_score
print(accuracy_score(result,y_test[0:1000]))

0.826
